function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "BitWise_operation"};
	this.sidHashMap["BitWise_operation"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "BitWise_operation:1"};
	this.sidHashMap["BitWise_operation:1"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "BitWise_operation:2"};
	this.sidHashMap["BitWise_operation:2"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/Bitwise AND"] = {sid: "BitWise_operation:6"};
	this.sidHashMap["BitWise_operation:6"] = {rtwname: "<Root>/Bitwise AND"};
	this.rtwnameHashMap["<Root>/Bitwise NOT"] = {sid: "BitWise_operation:5"};
	this.sidHashMap["BitWise_operation:5"] = {rtwname: "<Root>/Bitwise NOT"};
	this.rtwnameHashMap["<Root>/Bitwise NOT1"] = {sid: "BitWise_operation:10"};
	this.sidHashMap["BitWise_operation:10"] = {rtwname: "<Root>/Bitwise NOT1"};
	this.rtwnameHashMap["<Root>/Bitwise NOT2"] = {sid: "BitWise_operation:11"};
	this.sidHashMap["BitWise_operation:11"] = {rtwname: "<Root>/Bitwise NOT2"};
	this.rtwnameHashMap["<Root>/Bitwise OR1"] = {sid: "BitWise_operation:7"};
	this.sidHashMap["BitWise_operation:7"] = {rtwname: "<Root>/Bitwise OR1"};
	this.rtwnameHashMap["<Root>/Bitwise XOR"] = {sid: "BitWise_operation:8"};
	this.sidHashMap["BitWise_operation:8"] = {rtwname: "<Root>/Bitwise XOR"};
	this.rtwnameHashMap["<Root>/Bitwise XOR1"] = {sid: "BitWise_operation:9"};
	this.sidHashMap["BitWise_operation:9"] = {rtwname: "<Root>/Bitwise XOR1"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "BitWise_operation:3"};
	this.sidHashMap["BitWise_operation:3"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "BitWise_operation:12"};
	this.sidHashMap["BitWise_operation:12"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "BitWise_operation:13"};
	this.sidHashMap["BitWise_operation:13"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "BitWise_operation:14"};
	this.sidHashMap["BitWise_operation:14"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<Root>/Output4"] = {sid: "BitWise_operation:15"};
	this.sidHashMap["BitWise_operation:15"] = {rtwname: "<Root>/Output4"};
	this.rtwnameHashMap["<Root>/Output5"] = {sid: "BitWise_operation:16"};
	this.sidHashMap["BitWise_operation:16"] = {rtwname: "<Root>/Output5"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
