function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Calculator_subsystem"};
	this.sidHashMap["Calculator_subsystem"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Calculator_subsystem:3"};
	this.sidHashMap["Calculator_subsystem:3"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "Calculator_subsystem:1"};
	this.sidHashMap["Calculator_subsystem:1"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "Calculator_subsystem:2"};
	this.sidHashMap["Calculator_subsystem:2"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "Calculator_subsystem:3"};
	this.sidHashMap["Calculator_subsystem:3"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "Calculator_subsystem:14"};
	this.sidHashMap["Calculator_subsystem:14"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "Calculator_subsystem:15"};
	this.sidHashMap["Calculator_subsystem:15"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "Calculator_subsystem:16"};
	this.sidHashMap["Calculator_subsystem:16"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "Calculator_subsystem:17"};
	this.sidHashMap["Calculator_subsystem:17"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<S1>/Input"] = {sid: "Calculator_subsystem:4"};
	this.sidHashMap["Calculator_subsystem:4"] = {rtwname: "<S1>/Input"};
	this.rtwnameHashMap["<S1>/Input1"] = {sid: "Calculator_subsystem:5"};
	this.sidHashMap["Calculator_subsystem:5"] = {rtwname: "<S1>/Input1"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "Calculator_subsystem:6"};
	this.sidHashMap["Calculator_subsystem:6"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "Calculator_subsystem:7"};
	this.sidHashMap["Calculator_subsystem:7"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "Calculator_subsystem:8"};
	this.sidHashMap["Calculator_subsystem:8"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "Calculator_subsystem:9"};
	this.sidHashMap["Calculator_subsystem:9"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Output"] = {sid: "Calculator_subsystem:10"};
	this.sidHashMap["Calculator_subsystem:10"] = {rtwname: "<S1>/Output"};
	this.rtwnameHashMap["<S1>/Output1"] = {sid: "Calculator_subsystem:11"};
	this.sidHashMap["Calculator_subsystem:11"] = {rtwname: "<S1>/Output1"};
	this.rtwnameHashMap["<S1>/Output2"] = {sid: "Calculator_subsystem:12"};
	this.sidHashMap["Calculator_subsystem:12"] = {rtwname: "<S1>/Output2"};
	this.rtwnameHashMap["<S1>/Output3"] = {sid: "Calculator_subsystem:13"};
	this.sidHashMap["Calculator_subsystem:13"] = {rtwname: "<S1>/Output3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
